/*
 * Author: Root
 * Description: Converts a laptop object to an inventory item, preserving all state (filesystem, terminal, network, power).
 *
 * Arguments:
 * 0: _object <OBJECT> - The laptop object to convert
 * 1: _player <OBJECT> - The player picking up the laptop
 *
 * Return Value:
 * <BOOL> - True if successful, false otherwise
 *
 * Example:
 * [_laptop, player] call AE3_armaos_fnc_laptop_obj2item;
 *
 * Public: No
 */

params ["_object", "_player"];

private _itemClass = getText ((configOf _object) >> "ae3_item");

if (_itemClass == "") exitWith {
	hint "This laptop cannot be picked up into inventory.";
	false
};

private _buffer = missionNamespace getVariable ["AE3_LAPTOP_ITEM", createHashMap];

if (count _buffer > 511) exitWith {
	hint "Cannot carry more than 512 unique laptops at once.";
	false
};

// Get or assign a unique ID for this laptop
private _id = _object getVariable ["AE3_ITEM_ID", -1];
private _item = _itemClass + "_ID_";

if (_id == -1) then
{
	_id = 1;
	// Find available ID
	while {(_item + str _id) in _buffer} do
	{
		_id = _id + 1;
	};
	_object setVariable ["AE3_ITEM_ID", _id];
};

_item = _item + (str _id);

// Copy all object variables - this preserves ALL laptop state
// CRITICAL: Exclude variables containing TEXT (structured text) to prevent serialization warnings
// CRITICAL: Exclude all CODE references (functions) - they cannot be serialized and must be regenerated
// According to CLAUDE.md, never transmit TEXT via network - only raw STRING/ARRAY data
private _itemNamespace = createHashMap;
private _excludedVars = [
	"AE3_terminalRenderedBuffer",  // Contains TEXT - will be regenerated locally
	"AE3_terminalDialog",           // Display reference - not serializable
	"AE3_Links",                    // Command links - will be regenerated by fnc_link_init on deploy
	"AE3_computer_mutex",           // Runtime lock - should not persist
	"AE3_interaction_hasEquipmentAction",  // Runtime ACE interaction flag - will be re-added by init
	"AE3_interaction_laptopActionsAdded",  // Runtime flag - will be re-added by init
	"AE3_interaction_equipmentActionsAdded",  // Runtime flag - will be re-added by init
	"AE3_power_actionsAdded",       // Runtime flag - will be re-added by init
	// All CODE references must be excluded - they cannot serialize and will be regenerated by init
	"AE3_interaction_fnc_open",     // CODE - will be re-assigned by init
	"AE3_interaction_fnc_close",    // CODE - will be re-assigned by init
	"AE3_interaction_fnc_openWrapper",  // CODE - will be re-assigned by init
	"AE3_interaction_fnc_closeWrapper", // CODE - will be re-assigned by init
	"AE3_interaction_fnc_openActionCondition",  // CODE - will be re-assigned by init
	"AE3_interaction_fnc_closeActionCondition", // CODE - will be re-assigned by init
	"AE3_power_fnc_turnOn",         // CODE - will be re-assigned by init
	"AE3_power_fnc_turnOff",        // CODE - will be re-assigned by init
	"AE3_power_fnc_standby",        // CODE - will be re-assigned by init
	"AE3_power_fnc_turnOnWrapper",  // CODE - will be re-assigned by init
	"AE3_power_fnc_turnOffWrapper", // CODE - will be re-assigned by init
	"AE3_power_fnc_standbyWrapper", // CODE - will be re-assigned by init
	"AE3_power_fnc_turnOnCondition",  // CODE - will be re-assigned by init
	"AE3_power_fnc_turnOffCondition", // CODE - will be re-assigned by init
	"AE3_power_fnc_standbyCondition"  // CODE - will be re-assigned by init
];

{
	// Skip excluded variables that contain TEXT or non-serializable types
	if !(_x in _excludedVars) then {
		private _value = _object getVariable _x;
		if (!isNil "_value") then {
			_itemNamespace set [_x, _value];
		};
	};
} forEach (allVariables _object);

// Store original object class type for recreation
_itemNamespace set ["AE3_OBJECT_TYPE", typeOf _object];

// Store position and orientation for potential re-deployment at same location
_itemNamespace set ["AE3_ORIGINAL_POS", getPosATL _object];
_itemNamespace set ["AE3_ORIGINAL_DIR", getDir _object];

// Save to global buffer (server-side only - do NOT broadcast to avoid TEXT serialization)
// The buffer will be synced on-demand when deploying via fnc_getRemoteVar
_buffer set [_item, _itemNamespace];
missionNamespace setVariable ["AE3_LAPTOP_ITEM", _buffer, false]; // Server-side only, no broadcast

// Add item to player inventory
[_player, _item, true] remoteExecCall ["CBA_fnc_addItem", _player];

// Show feedback to player - show "Laptop N" based on ID
hint format ["Packed Laptop %1 into inventory", _id];

// Delete the ground object
deleteVehicle _object;

true
